/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/discovery-sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * S01 に出すセクションの一覧を取得する（F01（discovery-sections））
         * @description どのセクションをどの順で出すかは API が決める。中身（カード）は含めず、セクションごとに
         *     /discovery-sections/{sectionKey}/discoveries で取る。
         *
         *     - 今の提案の軸は「この近く」（nearby）と「今の時期」（season）の2つ（#89 の決定）。
         *       未ログインのため、興味（Subject）を使う軸は扱わない。
         *     - 一覧と中身を分けるのは、セクションごとに別々に読み込めるようにするため（モバイルは開いたタブの分だけ取る、
         *       PC は各セクションを並行して取る）。画面はセクションごとに読み込み中（C09（loading））を出す。
         *       あわせて、続きの読み込み（無限スクロール）や S02 への「もっと見る」、ログイン後の興味のセクションを足しやすくする。
         */
        get: operations["getDiscoverySections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery-sections/{sectionKey}/discoveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * S01 の1つのセクションのカード（C05（discovery-section）の中身）を取得する
         * @description セクションは推薦の候補を絞り込む条件であり、並び順ではない。どのセクションも、候補を推薦順（推薦度の高い順）で返す。
         *
         *     - nearby：いる場所の周辺にある Discovery の、推薦する Value（季節が一致、または通年・条件なし）を候補とする。
         *       季節違いの Value は候補にしない。
         *     - season：「今」の季節と一致する Value を候補とする。今は通年・条件なしの Value は候補にしない。
         *       季節は「今」の月から決める（3〜5月が春、など一般的な解釈）。
         *     - 対象は成立状態が ESTABLISHED かつ公開状態が PUBLIC の Discovery。
         *     - 1件のカードは、Discovery と、推薦の対象になった Value（valueId）の組。同じ Discovery が別の Value を伴って複数現れてよい。
         *     - 「周辺」の範囲と推薦度の評価ロジックは約束事に含めない（冒頭の「並び順は推薦順」を参照）。
         *
         *     続きの読み込みの単位（cursor 方式にするか等）は、S01 の無限スクロールを試すときに決める。今は limit までを返す。
         */
        get: operations["getDiscoverySectionItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discoveries/{discoveryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * S03 の Discovery の内容を取得する（みんなの声を除く）
         * @description タイトル、Hero（C19）、わかってきたこと（C25）、本文、タグ、その他の魅力（C12）、関係する Discovery（C03 の3つの枠）を返す。
         *     みんなの声（C26）は件数が増えるため、別の API（/discoveries/{discoveryId}/posts）で取る。
         *
         *     Value の振り分けは API が行い、画面では評価しない（S03「評価ロジックはC19に持たせず」）。
         *     - 推薦する Value（季節が一致、または通年・条件なし）→ `recommendations`（Hero）。推薦順（推薦度の高い順）
         *     - 推薦しない Value（季節違い）→ `otherValues`（その他の魅力）
         */
        get: operations["getDiscovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discoveries/{discoveryId}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * S03 のみんなの声（C26）を取得する
         * @description この Discovery を投稿先（器）とする声（Post）を、時系列（古い→新しい）で返す。ツリーにはしない。
         *     あわせて、派生の目印と、派生して生まれた Discovery の場合の元の会話を返す。
         *
         *     直近の表示件数・展開・ページ送りは未定（Issue #53）。今回はすべて返し、件数が増えたらページ送りの項目を足す。
         */
        get: operations["getDiscoveryPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 提案や Value の振り分けに使った「今」と「いる場所」。開発用の設定で固定したかどうかも返す */
        EvaluationContext: {
            /**
             * Format: date-time
             * @description 「今」
             */
            now: string;
            season: components["schemas"]["CurrentSeason"];
            location: components["schemas"]["Location"];
            /**
             * @description fixed は開発用の設定ファイルで固定した日時、system は実際の日時
             * @enum {string}
             */
            clockSource: "fixed" | "system";
            /**
             * @description fixed は開発用の設定ファイルで指定した場所、default は既定エリア（桜木町駅の付近）
             * @enum {string}
             */
            locationSource: "fixed" | "default";
        };
        Location: {
            /** @description 表示用の名前（例：桜木町駅） */
            name: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        /**
         * @description 「今」の季節
         * @enum {string}
         */
        CurrentSeason: "spring" | "summer" | "autumn" | "winter";
        /**
         * @description Value の条件としての季節（DEC-0002。春・夏・秋・冬・通年）
         * @enum {string}
         */
        Season: "spring" | "summer" | "autumn" | "winter" | "all_year";
        /**
         * @description 提案の軸。nearby は「この近く」、season は「今の時期」。軸が増えたら値を足す
         * @enum {string}
         */
        SectionKey: "nearby" | "season";
        DiscoverySectionList: {
            context: components["schemas"]["EvaluationContext"];
            /** @description 表示する順 */
            sections: components["schemas"]["DiscoverySection"][];
        };
        DiscoverySection: {
            key: components["schemas"]["SectionKey"];
            /** @description セクションの表示名（PC の見出し、モバイルのタブ） */
            title: string;
        };
        DiscoverySectionItems: {
            context: components["schemas"]["EvaluationContext"];
            key: components["schemas"]["SectionKey"];
            /** @description 推薦順（推薦度の高い順）。0件のこともある（見せ方は画面で決める） */
            items: components["schemas"]["RecommendedDiscoveryCard"][];
        };
        /** @description 推薦の候補としてのカード。Discovery と、推薦の対象になった Value の組 */
        RecommendedDiscoveryCard: components["schemas"]["DiscoveryCard"] & {
            /** @description 推薦の対象になった Value。同じ Discovery が複数現れる場合の区別にもなる */
            valueId: string;
        };
        /** @description C03（discovery-card）。Discovery と、代表して見せる Value の要約 */
        DiscoveryCard: {
            id: string;
            title: string;
            /** @description 何についての価値か（例：桜並木、散策） */
            subject: string;
            /** @description 代表して見せる Value の短い説明 */
            value: string;
            picture?: components["schemas"]["Image"];
            place: components["schemas"]["PlaceSummary"];
        };
        /** @description 場所。地図は埋め込まず、テキストで表示する */
        PlaceSummary: {
            /** @description 例：大岡川（桜木町駅〜蒔田） */
            name: string;
        };
        /** @description 画像。今回のサンプルは権利の問題を避けるため仮の画像 */
        Image: {
            /** Format: uri-reference */
            url: string;
            alt: string;
        };
        /** @description 別の Discovery への参照（派生の誘導の表示用） */
        DiscoveryRef: {
            id: string;
            title: string;
        };
        DiscoveryDetail: {
            id: string;
            title: string;
            /** @description 本文（現在の要約） */
            body: string;
            place: components["schemas"]["PlaceSummary"];
            context: components["schemas"]["EvaluationContext"];
            /** @description Hero（C19）に渡す、推薦する Value。推薦順（推薦度の高い順）。0件でも Hero は標準 Hero で表示する（Issue */
            recommendations: components["schemas"]["Recommendation"][];
            /** @description その他の魅力（C12）。季節違いで、今は推薦しない Value */
            otherValues: components["schemas"]["ValueItem"][];
            /** @description わかってきたこと（C25）。説と価値 */
            findings: components["schemas"]["Finding"][];
            /** @description Discovery のタグ。属する声のタグと、運営が付けたタグを集めたもの */
            tags: string[];
            reactions: components["schemas"]["DiscoveryReactions"];
            relations: components["schemas"]["DiscoveryRelations"];
        };
        /** @description C19（Discovery詳細 Hero）の1件分 */
        Recommendation: {
            valueId: string;
            /**
             * @description 今伝えたい価値のメッセージ（例：今、桜が見頃です）。
             *     価値の組み合わせと会話の文脈を AI で解析した結果として作る文言を想定する。
             *     今回のサンプルでは、解析の結果の代わりに、用意した文言をデータとして持つ
             */
            message: string;
            /** @description 参加を促すメッセージ（例：一緒に考えませんか？） */
            participationMessage?: string;
            media?: components["schemas"]["Image"];
        };
        /** @description C12（discovery-value）の1件分 */
        ValueItem: {
            id: string;
            /** @description 何についての価値か */
            subject: string;
            value: string;
            body: string;
            picture?: components["schemas"]["Image"];
            /** @description 楽しめる条件の説明。内部の Condition の構造をそのまま出さず、表示用の説明にする */
            conditions: components["schemas"]["ConditionDescription"][];
        };
        ConditionDescription: {
            /** @description 例：季節 */
            label: string;
            /** @description 例：春（3〜5月） */
            text: string;
            /** @description 季節の条件の場合の値（画面で表示を変えたいとき用） */
            seasons?: components["schemas"]["Season"][];
        };
        /**
         * @description C25（わかってきたこと）の1件分。まだ見立てであり、断定の書き方にしない。
         *     リアクションの有無は種類と裏付けで決まる（DEC-0009 決定9）。
         *
         *     | 種類 | backedBy | reactions |
         *     |---|---|---|
         *     | 価値（value） | なし | あり（understand・wantToGo） |
         *     | 裏付けのない説（theory） | なし | あり（maybe） |
         *     | 裏付けのある説（theory） | あり | なし（項目自体を返さない） |
         */
        Finding: {
            id: string;
            /**
             * @description value は価値、theory は説
             * @enum {string}
             */
            kind: "value" | "theory";
            text: string;
            /** @description 資料（出典）の裏付けがある説の出典名。説（theory）だけが持つ。ある場合は reactions を返さない */
            backedBy?: string;
            /**
             * @description 種類ごとのリアクション数。価値は understand（わかる）・wantToGo（行ってみたい）、裏付けのない説は maybe（そうかも）。
             *     裏付けのある説（backedBy がある）では返さない
             */
            reactions?: {
                understand?: number;
                wantToGo?: number;
                maybe?: number;
            };
        };
        /** @description Discovery へのリアクション数（C10。👍／😮／♥） */
        DiscoveryReactions: {
            like: number;
            surprised: number;
            love: number;
        };
        /** @description 関係する Discovery の3つの枠。該当がない枠は空の配列 */
        DiscoveryRelations: {
            /** @description 派生元（この発見のもとになった Discovery） */
            derivedFrom: components["schemas"]["DiscoveryCard"][];
            /** @description 派生した Discovery（この発見から広がった Discovery） */
            derivedTo: components["schemas"]["DiscoveryCard"][];
            /** @description 関連する Discovery。今回はベクトル検索を使わず、サンプルデータに書いた関係をそのまま返す */
            related: components["schemas"]["DiscoveryCard"][];
        };
        DiscoveryPosts: {
            /** @description 時系列（古い→新しい） */
            posts: components["schemas"]["Post"][];
            /** @description 派生の目印。afterPostId の声の直後に挟む */
            derivationMarkers: components["schemas"]["DerivationMarker"][];
            /** @description 派生して生まれた Discovery の場合の元の会話（一覧の冒頭に示す） */
            derivedOrigin?: components["schemas"]["DiscoveryRef"];
        };
        /** @description 声（Post）。C26（みんなの声）の1件分 */
        Post: {
            id: string;
            /** @description 投稿者の今のニックネーム（声に名前は保存せず、表示のたびに引く。Issue */
            authorName: string;
            /**
             * Format: date-time
             * @description 投稿日時。相対表現（n日前 等）は画面で作る
             */
            postedAt: string;
            /** @description 本文。#タグを含め、ユーザーが書いたまま */
            body: string;
            replyTo?: components["schemas"]["ReplyQuote"];
            /** @description この声とともに Discovery へ提供された資料 */
            media: components["schemas"]["MediaItem"][];
            /** @description 声への共感の数 */
            reactionCount: number;
            /** @description 派生した話の続きと見立てられた場合の派生先（「『〇〇』で続いています」） */
            continuedIn?: components["schemas"]["DiscoveryRef"];
        };
        /** @description 返信先の引用（Post 間の参照。PostReference） */
        ReplyQuote: {
            postId: string;
            authorName: string;
            /** @description 返信先の本文の冒頭 */
            excerpt: string;
        };
        MediaItem: {
            id: string;
            /** @enum {string} */
            kind: "image" | "video" | "pdf" | "other";
            name: string;
            /** @description kind が image の場合の画像 */
            image?: components["schemas"]["Image"];
            source: components["schemas"]["MediaSource"];
        };
        /** @description 資料の出典（C23（資料出典登録ダイアログ）で登録するもの） */
        MediaSource: {
            /**
             * @description unset は未設定、self は自分で撮影・作成、registered は出典を登録済み、unknown は不明
             * @enum {string}
             */
            status: "unset" | "self" | "registered" | "unknown";
            /** @enum {string} */
            type?: "website" | "book" | "document" | "provided" | "other";
            name?: string;
        };
        DerivationMarker: {
            afterPostId: string;
            discovery: components["schemas"]["DiscoveryRef"];
        };
        /** @description RFC 9457 Problem Details */
        Problem: {
            /** Format: uri-reference */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
        };
    };
    responses: {
        /** @description 指定が正しくない（例：limit が範囲外、discoveryId が長すぎる） */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Discovery がない、または公開状態が HIDDEN */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description セクションの key（/discovery-sections で返したもの） */
        SectionKey: components["schemas"]["SectionKey"];
        /** @description Discovery の識別子。形式は約束しない（中身を解釈しない文字列として扱う） */
        DiscoveryId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDiscoverySections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description セクションの一覧（表示する順） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverySectionList"];
                };
            };
        };
    };
    getDiscoverySectionItems: {
        parameters: {
            query?: {
                /** @description 最大件数 */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description セクションの key（/discovery-sections で返したもの） */
                sectionKey: components["parameters"]["SectionKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description セクションのカード */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverySectionItems"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description セクションがない（一覧にない key を指定した） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getDiscovery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Discovery の識別子。形式は約束しない（中身を解釈しない文字列として扱う） */
                discoveryId: components["parameters"]["DiscoveryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovery の内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getDiscoveryPosts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Discovery の識別子。形式は約束しない（中身を解釈しない文字列として扱う） */
                discoveryId: components["parameters"]["DiscoveryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description みんなの声 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryPosts"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
